//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulamaKoparatifi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SULAMADBEntities1 : DbContext
    {
        public SULAMADBEntities1()
            : base("name=SULAMADBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UyeTbl> UyeTbl { get; set; }
        public virtual DbSet<GorTbl> GorTbl { get; set; }
        public virtual DbSet<OdeTbl> OdeTbl { get; set; }
        public virtual DbSet<PompaTbl> PompaTbl { get; set; }
        public virtual DbSet<SuTbl> SuTbl { get; set; }
    }
}
