//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulamaKoparatifi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdeTbl
    {
        public int odeuye { get; set; }
        public string odead { get; set; }
        public string odetc { get; set; }
        public string odetarih { get; set; }
        public string odesez { get; set; }
        public string odemak { get; set; }
        public decimal odetutar { get; set; }
        public decimal odemik { get; set; }
        public decimal odekalan { get; set; }
        public string odetur { get; set; }
    }
}
