//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulamaKoparatifi
{
    using System;
    using System.Collections.Generic;
    
    public partial class PompaTbl
    {
        public int pompanu { get; set; }
        public string pompais { get; set; }
        public int pompauc { get; set; }
    }
}
