//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulamaKoparatifi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuTbl
    {
        public int uyesu { get; set; }
        public string tcsu { get; set; }
        public string adsu { get; set; }
        public string fisu { get; set; }
        public string actarihsu { get; set; }
        public string kapatarihsu { get; set; }
        public string sumevki { get; set; }
        public string susez { get; set; }
        public string sugor { get; set; }
        public decimal suucret { get; set; }
        public string toplamsaat { get; set; }
        public decimal sutoplam { get; set; }
    }
}
