//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SulamaKoparatifi
{
    using System;
    using System.Collections.Generic;
    
    public partial class UyeTbl
    {
        public int idu { get; set; }
        public string adu { get; set; }
        public string babau { get; set; }
        public string anneu { get; set; }
        public string tcu { get; set; }
        public string telu { get; set; }
        public string teladres { get; set; }
        public string aciku { get; set; }
        public string sulau { get; set; }
        public string ortu { get; set; }
        public string opu { get; set; }
        public string odeu { get; set; }
        public string kalu { get; set; }
        public string giru { get; set; }
        public string karu { get; set; }
        public string knu { get; set; }
        public string dnu { get; set; }
    }
}
